export const ROLE_ADMIN = "ADMIN";
export const ROLE_STORE = "STORE";
export const ROLE_PURCHASE = "PURCHASE";
export const ROLE_USER = "USER";

export const CATEGORY_CONSTANTS = {
  CATEGORY_FETCH_PROGRESS: 'CATEGORY_FETCH_PROGRESS',
  CATEGORY_FETCH_SUCCESS: 'CATEGORY_FETCH_SUCCESS',
  CATEGORY_FETCH_FAIL: 'CATEGORY_FETCH_FAIL',
  CATEGORY_ADD_FORM_TOGGLE: 'CATEGORY_ADD_FORM_TOGGLE',
  CATEGORY_ADD_SUCCESS: 'CATEGORY_ADD_SUCCESS',
  CATEGORY_ADD_FAIL: 'CATEGORY_ADD_FAIL',
  CATEGORY_EDIT_FORM_TOGGLE: 'CATEGORY_EDIT_FORM_TOGGLE',
  CATEGORY_EDIT_SUCCESS: 'CATEGORY_EDIT_SUCCESS',
  CATEGORY_EDIT_FAIL: 'CATEGORY_EDIT_FAIL',
  CATEGORY_REMOVE_PROGRESS: 'CATEGORY_REMOVE_PROGRESS',
  CATEGORY_REMOVE_SUCCESS: 'CATEGORY_REMOVE_SUCCESS',
  CATEGORY_REMOVE_FAIL: 'CATEGORY_REMOVE_FAIL',
  CATEGORY_FILTER: 'CATEGORY_FILTER',
  CATEGORY_SORT: 'CATEGORY_SORT'
};

export const SUB_CATEGORY_CONSTANTS = {
  SUB_CATEGORY_FETCH_PROGRESS: 'SUB_CATEGORY_FETCH_PROGRESS',
  SUB_CATEGORY_FETCH_SUCCESS: 'SUB_CATEGORY_FETCH_SUCCESS',
  SUB_CATEGORY_FETCH_FAIL: 'SUB_CATEGORY_FETCH_FAIL',
  SUB_CATEGORY_ADD_FORM_TOGGLE: 'SUB_CATEGORY_ADD_FORM_TOGGLE',
  SUB_CATEGORY_ADD_SUCCESS: 'SUB_CATEGORY_ADD_SUCCESS',
  SUB_CATEGORY_ADD_FAIL: 'SUB_CATEGORY_ADD_FAIL',
  SUB_CATEGORY_EDIT_FORM_TOGGLE: 'SUB_CATEGORY_EDIT_FORM_TOGGLE',
  SUB_CATEGORY_EDIT_SUCCESS: 'SUB_CATEGORY_EDIT_SUCCESS',
  SUB_CATEGORY_EDIT_FAIL: 'SUB_CATEGORY_EDIT_FAIL',
  SUB_CATEGORY_REMOVE_PROGRESS: 'SUB_CATEGORY_REMOVE_PROGRESS',
  SUB_CATEGORY_REMOVE_SUCCESS: 'SUB_CATEGORY_REMOVE_SUCCESS',
  SUB_CATEGORY_REMOVE_FAIL: 'SUB_CATEGORY_REMOVE_FAIL'
};
