export const ROLE_ADMIN = "ADMIN";
export const ROLE_STORE = "STORE";
export const ROLE_PURCHASE = "PURCHASE";
export const ROLE_USER = "USER";

export const CATEGORY_CONSTANTS = {
  CATEGORY_FETCH_PROGRESS: 'CATEGORY_FETCH_PROGRESS',
  CATEGORY_FETCH_SUCCESS: 'CATEGORY_FETCH_SUCCESS',
  CATEGORY_FETCH_FAIL: 'CATEGORY_FETCH_FAIL',
  CATEGORY_ADD_FORM_TOGGLE: 'CATEGORY_ADD_FORM_TOGGLE',
  CATEGORY_ADD_SUCCESS: 'CATEGORY_ADD_SUCCESS',
  CATEGORY_ADD_FAIL: 'CATEGORY_ADD_FAIL',
  CATEGORY_EDIT_FORM_TOGGLE: 'CATEGORY_EDIT_FORM_TOGGLE',
  CATEGORY_EDIT_SUCCESS: 'CATEGORY_EDIT_SUCCESS',
  CATEGORY_EDIT_FAIL: 'CATEGORY_EDIT_FAIL',
  CATEGORY_REMOVE_PROGRESS: 'CATEGORY_REMOVE_PROGRESS',
  CATEGORY_REMOVE_SUCCESS: 'CATEGORY_REMOVE_SUCCESS',
  CATEGORY_REMOVE_FAIL: 'CATEGORY_REMOVE_FAIL',
  CATEGORY_FILTER: 'CATEGORY_FILTER',
  CATEGORY_SORT: 'CATEGORY_SORT'
};

export const SUB_CATEGORY_CONSTANTS = {
  SUB_CATEGORY_FETCH_PROGRESS: 'SUB_CATEGORY_FETCH_PROGRESS',
  SUB_CATEGORY_FETCH_SUCCESS: 'SUB_CATEGORY_FETCH_SUCCESS',
  SUB_CATEGORY_FETCH_FAIL: 'SUB_CATEGORY_FETCH_FAIL',
  SUB_CATEGORY_ADD_FORM_TOGGLE: 'SUB_CATEGORY_ADD_FORM_TOGGLE',
  SUB_CATEGORY_ADD_SUCCESS: 'SUB_CATEGORY_ADD_SUCCESS',
  SUB_CATEGORY_ADD_FAIL: 'SUB_CATEGORY_ADD_FAIL',
  SUB_CATEGORY_EDIT_FORM_TOGGLE: 'SUB_CATEGORY_EDIT_FORM_TOGGLE',
  SUB_CATEGORY_EDIT_SUCCESS: 'SUB_CATEGORY_EDIT_SUCCESS',
  SUB_CATEGORY_EDIT_FAIL: 'SUB_CATEGORY_EDIT_FAIL',
  SUB_CATEGORY_REMOVE_PROGRESS: 'SUB_CATEGORY_REMOVE_PROGRESS',
  SUB_CATEGORY_REMOVE_SUCCESS: 'SUB_CATEGORY_REMOVE_SUCCESS',
  SUB_CATEGORY_REMOVE_FAIL: 'SUB_CATEGORY_REMOVE_FAIL'
};

export const SECTION_CONSTANTS = {
  SECTION_FETCH_PROGRESS: 'SECTION_FETCH_PROGRESS',
  SECTION_FETCH_SUCCESS: 'SECTION_FETCH_SUCCESS',
  SECTION_FETCH_FAIL: 'SECTION_FETCH_FAIL',
  SECTION_ADD_FORM_TOGGLE: 'SECTION_ADD_FORM_TOGGLE',
  SECTION_ADD_SUCCESS: 'SECTION_ADD_SUCCESS',
  SECTION_ADD_FAIL: 'SECTION_ADD_FAIL',
  SECTION_EDIT_FORM_TOGGLE: 'SECTION_EDIT_FORM_TOGGLE',
  SECTION_EDIT_SUCCESS: 'SECTION_EDIT_SUCCESS',
  SECTION_EDIT_FAIL: 'SECTION_EDIT_FAIL',
  SECTION_REMOVE_PROGRESS: 'SECTION_REMOVE_PROGRESS',
  SECTION_REMOVE_SUCCESS: 'SECTION_REMOVE_SUCCESS',
  SECTION_REMOVE_FAIL: 'SECTION_REMOVE_FAIL'
};

export const SUPPLIER_CONSTANTS = {
  SUPPLIER_FETCH_PROGRESS: 'SUPPLIER_FETCH_PROGRESS',
  SUPPLIER_FETCH_SUCCESS: 'SUPPLIER_FETCH_SUCCESS',
  SUPPLIER_FETCH_FAIL: 'SUPPLIER_FETCH_FAIL',
  SUPPLIER_ADD_FORM_TOGGLE: 'SUPPLIER_ADD_FORM_TOGGLE',
  SUPPLIER_ADD_SUCCESS: 'SUPPLIER_ADD_SUCCESS',
  SUPPLIER_ADD_FAIL: 'SUPPLIER_ADD_FAIL',
  SUPPLIER_EDIT_FORM_TOGGLE: 'SUPPLIER_EDIT_FORM_TOGGLE',
  SUPPLIER_EDIT_SUCCESS: 'SUPPLIER_EDIT_SUCCESS',
  SUPPLIER_EDIT_FAIL: 'SUPPLIER_EDIT_FAIL',
  SUPPLIER_REMOVE_PROGRESS: 'SUPPLIER_REMOVE_PROGRESS',
  SUPPLIER_REMOVE_SUCCESS: 'SUPPLIER_REMOVE_SUCCESS',
  SUPPLIER_REMOVE_FAIL: 'SUPPLIER_REMOVE_FAIL',
  SUPPLIER_FILTER: 'SUPPLIER_FILTER',
  SUPPLIER_SORT: 'SUPPLIER_SORT'
};

export const PRODUCT_CONSTANTS = {
  PRODUCT_FETCH_PROGRESS: 'PRODUCT_FETCH_PROGRESS',
  PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS',
  PRODUCT_FETCH_FAIL: 'PRODUCT_FETCH_FAIL',
  PRODUCT_ADD_FORM_TOGGLE: 'PRODUCT_ADD_FORM_TOGGLE',
  PRODUCT_ADD_SUCCESS: 'PRODUCT_ADD_SUCCESS',
  PRODUCT_ADD_FAIL: 'PRODUCT_ADD_FAIL',
  PRODUCT_EDIT_FORM_TOGGLE: 'PRODUCT_EDIT_FORM_TOGGLE',
  PRODUCT_EDIT_SUCCESS: 'PRODUCT_EDIT_SUCCESS',
  PRODUCT_EDIT_FAIL: 'PRODUCT_EDIT_FAIL',
  PRODUCT_REMOVE_PROGRESS: 'PRODUCT_REMOVE_PROGRESS',
  PRODUCT_REMOVE_SUCCESS: 'PRODUCT_REMOVE_SUCCESS',
  PRODUCT_REMOVE_FAIL: 'PRODUCT_REMOVE_FAIL',
  PRODUCT_FILTER: 'PRODUCT_FILTER',
  PRODUCT_SORT: 'PRODUCT_SORT'
};
