export const ROLE_ADMIN = "ADMIN";
export const ROLE_STORE = "STORE";
export const ROLE_PURCHASE = "PURCHASE";
export const ROLE_USER = "USER";

export const CATEGORY_CONSTANTS = {
  CATEGORY_FETCH_PROGRESS: 'CATEGORY_FETCH_PROGRESS',
  CATEGORY_FETCH_SUCCESS: 'CATEGORY_FETCH_SUCCESS',
  CATEGORY_FETCH_FAIL: 'CATEGORY_FETCH_FAIL',
  CATEGORY_ADD_PROGRESS: 'CATEGORY_ADD_PROGRESS',
  CATEGORY_ADD_SUCCESS: 'CATEGORY_ADD_SUCCESS',
  CATEGORY_ADD_FAIL: 'CATEGORY_ADD_FAIL',
  CATEGORY_EDIT_PROGRESS: 'CATEGORY_EDIT_PROGRESS',
  CATEGORY_EDIT_SUCCESS: 'CATEGORY_EDIT_SUCCESS',
  CATEGORY_EDIT_FAIL: 'CATEGORY_EDIT_FAIL',
  CATEGORY_REMOVE_PROGRESS: 'CATEGORY_REMOVE_PROGRESS',
  CATEGORY_REMOVE_SUCCESS: 'CATEGORY_REMOVE_SUCCESS',
  CATEGORY_REMOVE_FAIL: 'CATEGORY_REMOVE_FAIL'
};
